project_id = "espfbkxgmewmpufsnkni"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.reset-all]
verify_jwt = true
